### ISSUE TITLE
How to use MegAmisDevTools

### ISSUE THREAD

**Issue by Eggmanplant** [MegAmi24/Mania-Decomp-Mods#4]
How to use MegAmisDevTools? I tried every key but it doesn't seem to work.

**Comment by MegAmi24** [comment]
It's the select button. I forget which key it's mapped to by default, but you can remap it in the dev menu.

**Comment by Eggmanplant** [comment]
None of the keys on the US keyboard layout seems to be the select key.

**Comment by MegAmi24** [comment]
When I say select, I'm referring to one of the things that RSDK recognizes as a controller input. I am not referring to an actual physical keyboard key.

**Comment by Eggmanplant** [comment]
Yes. I know.

czw., 14 gru 2023 o 19:19 MegAmi ***@***.***> napisał(a):
